# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 981c32b58ba40d2827c4f8057433eba605015da5896fe827897d6172499910b2d62b32647ab719b591628d3604b9c6535d983a36e9f1f8855bc6d28ac719074e

test:
  secret_key_base: d6cc80c971c491065650a0ffd8e4213acac6db434e56309222a3685bf4e94215cca63edf76fff3cc39b60cef5836e51f336f882ffe4079173120d8cf2781900f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
